#cloud-config
users: # Dies ist der Beginn einer Liste von Benutzerkonfigurationen
  - name: ubuntu # Hier wird ein Benutzer mit dem Namen ubuntu erstellt
    sudo: ALL=(ALL) NOPASSWD:ALL # Dies ermöglicht dem Benutzer ubuntu, alle Befehle mit administrativen Rechten ohne Passwortabfrage auszuführen
    groups: users, admin # Der Benutzer ubuntu wird den Gruppen users und admin hinzugefügt
    home: /home/ubuntu # Dies legt das Heimatverzeichnis des Benutzers ubuntu auf /home/ubuntu fest
    shell: /bin/bash # Der Benutzer ubuntu verwendet die Bash-Shell
    ssh_authorized_keys: #  Hier können öffentliche SSH-Schlüssel für die Benutzerauthentifizierung hinzugefügt werden. In diesem Beispiel wird ein SSH-Schlüssel (Beginnend mit ssh-rsa) angegeben
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjeUEfHF/l/T1tYThfhEOO/SN+QLaCy9uLQ+uaZE25DHqclEilkz5xU2umEa4D1M3g2xZNcGeUEzUd0lXkeHjXzZpyPqoJ8bZaPvH7zPniWKOiIn/j/CrbqSS34GT29gHd171dlYKz0cc3gmfKIZia0CKz8QmYqPDBe9i9mEX5oMrS1juXdbtOJb4RLCMomHptn0hJoM+orqCVJ5eIHvku26YaP0TOwpdlH6k9EVVNBN1bRU8e1ymnz+xRP1tJTJMLtvrSqdYjfn4TcsOqF3M7Yos2fRf/j46N74rcevbGrqrL43cUMyc65ar8V+zJL9y3LSQMy0xr8xb+VNDnHi9X aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key

ssh_pwauth: false # Die SSH-Passwortauthentifizierung ist deaktiviert
disable_root: false # Die Root-Authentifizierung ist nicht deaktiviert, was bedeutet, dass der Root-Benutzer weiterhin SSH verwenden kann
package_update: true # Dies bedeutet, dass das System nach der Konfiguration auf aktualisierte Pakete überprüft werden soll
packages: # Hier werden Pakete aufgelistet, die auf dem System installiert werden sollen. In diesem Fall sind es curl und wget
  - curl
  - wget
